export const WINDOW_DEFINITIONS = {
    terminal: {
        id: 'terminal',
        title: 'MS-DOS Prompt - C:',
        component: 'terminal',
        position: { x: 100, y: 100 },
        size: { width: 640, height: 480 },
    },
    'history-log': {
        id: 'history-log',
        title: 'Notepad - HISTORY.TXT',
        component: 'history-log',
        position: { x: 300, y: 100 },
        size: { width: 650, height: 500 },
    },
    'winamp': {
        id: 'winamp',
        title: 'Winamp',
        component: 'winamp',
        position: { x: 400, y: 50 },
        size: { width: 275, height: 240 },
    },
    'artmoney': {
        id: 'artmoney',
        title: 'ArtMoney SE v1.0',
        component: 'artmoney',
        position: { x: 100, y: 100 },
        size: { width: 400, height: 300 },
    },
    'tmail-config': {
        id: 'tmail-config',
        title: 'T-Mail Setup',
        component: 'tmail-config',
        position: { x: 200, y: 100 },
        size: { width: 600, height: 500 },
    },
    'golded-config': {
        id: 'golded-config',
        title: 'GoldED Setup',
        component: 'golded-config',
        position: { x: 250, y: 150 },
        size: { width: 600, height: 500 },
    },
    'golded-reader': {
        id: 'golded-reader',
        title: 'GoldED 2.50+',
        component: 'golded-reader',
        position: { x: 150, y: 100 },
        size: { width: 800, height: 600 },
    },
    'radio-market': {
        id: 'radio-market',
        title: 'Радиорынок - Мир Электроники',
        component: 'radio-market',
        position: { x: 100, y: 50 },
        size: { width: 600, height: 500 },
    },
    'binkley-config': {
        id: 'binkley-config',
        title: 'BinkleyTerm Setup',
        component: 'binkley-config',
        position: { x: 200, y: 150 },
        size: { width: 600, height: 500 },
    },
    'binkley-term': {
        id: 'binkley-term',
        title: 'BinkleyTerm - Node 2:5020/730',
        component: 'binkley-term',
        position: { x: 50, y: 50 },
        size: { width: 800, height: 600 },
    },
    'quest-journal': {
        id: 'quest-journal',
        title: 'Активный квест',
        component: 'quest-journal',
        position: { x: 150, y: 100 },
        size: { width: 700, height: 650 },
    },
};
